### ISSUE TITLE
How can I arrange file order?

### ISSUE THREAD

**Issue by dogos1** [sizious/bootmake#1]
I have used Bootmake 1.2 for making selfboot cdi image file. It is very convenient and intuitive application.
But It seems that It doesn't supports to arrange file order..
I remembered that When I followed TuxTheWise's guide in order to make selfboot cdi image file, It was possible to arrange file order by making use of isobuster and listorganizer.exe.
I really want to arrange file order to shorten load time.
How can I arrange file order in Bootmake?
and Is it possible to make selfboot cdi image file of many CDDA track with Bootmake?

**Comment by sizious** [comment]
This is managed with mkisofs. You will have a `sorttxt` argument for accomplish this.

**Comment by sizious** [comment]
Sorry I missed your last question, currently cdi4dc doesn't support CDDA tracks. This is only supported on mds4dc.
